
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'morocco_banks_reviews'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'morocco_banks_reviews'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "logs"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  morocco_banks_reviews:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +docs:
        node_color: "lightblue"
    intermediate:
      +materialized: view
      +docs:
        node_color: "orange"
    marts:
      +materialized: table
      +docs:
        node_color: "green"

      dim_bank:
        +materialized: table
        +docs:
          description: "Dimension des banques"
      dim_branch:
        +materialized: table
        +docs:
          description: "Dimension des agences"
      dim_location:
        +materialized: table
        +docs:
          description: "Dimension des localisations"
      dim_sentiment:
        +materialized: table
        +docs:
          description: "Dimension des sentiments"
      dim_topic:
        +materialized: table
        +docs:
          description: "Dimension des topics"
      fact_reviews:
        +materialized: table
        +docs:
          description: "Table de faits des avis"
        +indexes:
          - columns: ['bank_key']
          - columns: ['location_key']
          - columns: ['review_date']

vars:
  # Variables pour le nettoyage
  min_review_length: 5
  max_review_length: 2000
  duplicate_threshold_days: 
